version: '2.1'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH}\nginx\certificates:/etc/nginx/certificates
      - ${PATH}\nginx\conf:/etc/nginx/conf.d
    links:
      - ghost-original
  ghost:
    image: ghost:${VERSION}-alpine
    restart: always
    container_name: ghost-original
    ports:
      - 8080:2368
    volumes:
      - ${PATH}\db:/var/lib/ghost/content
    environment:
      url: ${URL}